#! /system/bin/sh

rmmod pl2303
# number of USB device should be updated for your own
echo -n "2-1.1.3:1.0" > /sys/bus/usb/drivers/option/unbind
rmmod pl2303

insmod /system/lib/modules/pl2303.ko
sleep 2
busybox chmod 666 /dev/ttyUSB0
busybox stty -F /dev/ttyUSB0 ispeed 4800
busybox chmod 666 /dev/ttyUSB0
sleep 1
setprop "ro.kernel.android.gps" "ttyUSB0"
busybox chmod 666 /dev/ttyUSB0